//! SeaORM Entity. Generated by sea-orm-codegen 0.9.1

pub use super::product::Entity as SeaOrmProduct;
pub use super::product_category::Entity as SeaOrmProductCategory;
pub use super::user::Entity as SeaOrmUser;
